{"name": "Авторизация под пользователем, который есть в системе", "status": "passed", "description": "При авторизация под пользователем, который есть в системе, происходит успешная авторизация", "start": 1732633736103, "stop": 1732633737366, "uuid": "5453cf8f-1177-42f9-a662-3c3e66aeebc4", "historyId": "c1ee95458348aabac0acb25665322199", "testCaseId": "c1ee95458348aabac0acb25665322199", "fullName": "tests.test_login_user.Testlogin#test_login_user", "labels": [{"name": "suite", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "Testlogin"}, {"name": "host", "value": "Raybook"}, {"name": "thread", "value": "3488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}